INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('First User', 20, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Second User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Third User', 22, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Fourth User', 23, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Fifth User', 22, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Sixth User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Seventh User', 20, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Eighth User', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Ninth User', 18, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Tenth User', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User1', 19, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User2', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User3', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User4', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User5', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User6', 19, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User7', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User8', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User9', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User10', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User11', 19, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User12', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User13', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User14', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('User15', 19, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('Test User', 30, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 1, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
INSERT INTO test.user (name, age, isAdmin, createdDate) VALUES ('New User', 21, 0, NOW());
